# -*- coding: utf-8 -*-
"""population6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pdGlzZly9e-nyq4F_DdOaJOD-P7Pq_j5
"""

import numpy as np
import requests
import pandas as pd
from io import StringIO
import warnings
warnings.filterwarnings('ignore')

train = 'https://drive.google.com/file/d/17Xe8WLzwfdrO2MjQyjF9Xe_Dkr16LtPJ/view?usp=drivesdk'

def read_csv(url):

  url = 'https://drive.google.com/uc?export=download&id=' + url.split('/')[-2]
  csv_raw = requests.get(url).text
  csv = StringIO(csv_raw)
  df = pd.read_csv(csv)
  return df

#train = 'https://drive.google.com/file/d/17Xe8WLzwfdrO2MjQyjF9Xe_Dkr16LtPJ/view?usp=drivesdk'
df = read_csv(train)
df

df['percentage_schooling'] = df.percentage_primary_schooling + df.percentage_secondary_schooling + df.percentage_tertiary_schooling
df['illiterate_ratio'] = (df.percentage_no_schooling) / (df.percentage_schooling)
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.fillna(0, inplace=True)
df['illiterate_pop'] = ((df.illiterate_ratio * df.literate_pop)+0.5).round(0)
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.fillna(0, inplace=True)
df['population'] = df.literate_pop + df.illiterate_pop
df['target'] = ((df.literate_pop) / df.population) * 100
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.fillna(0, inplace=True)
pred = df[['ID','target']]
pred.to_csv('pred.csv',index=False)
pred





